import java.sql.SQLOutput;

public class oopodevi {
    public static void main(String[] args){
        dersgunleri pazartesi = new dersgunleri("matematik","edebiyat","beden");
        dersgunleri sali = new dersgunleri("ingilizcewriting","resim","ingilizcewriting");
        dersgunleri carsamba = new dersgunleri("matematik","ingilizcelistenig","ingilizcemaincourse");
        dersgunleri persembe = new dersgunleri("edebiyat","ingilizcemaincourse","bilisim");
        dersgunleri cuma = new dersgunleri("resim","ingilizcelistening","matematik");
        dersler matematik = new dersler("ünitesoruları","murat hoca",90,85);
        dersler edebiyat = new dersler("metin soruları","mustafa hoca",80,90);
        dersler ingilizcewriting = new dersler("writing an essay","hülya hoca",90,75);
        dersler ingilizcelistening = new dersler("finding unknown words","nermin hoca",89,79);
        dersler ingilzcemaincourse = new dersler("finishing the book","erman hoca",90,95);
        dersler bilisim = new dersler("ortalama hesaplayan kod","özgür hoca",100,60);
        dersler beden = new dersler("60 sayılık ritim","yılmaz hoca",100,100);
        dersler resim = new dersler("resim çizme","çiğdem hoca",70,85);

        System.out.println("PROGRAM:");
        System.out.println(pazartesi.birinciders);
        System.out.println("ödev");
        System.out.println(matematik.odev);
        System.out.println("giren hoca");
        System.out.println(matematik.girenhoca);
        System.out.println("yazılı notu");
        System.out.println(matematik.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(matematik.sozlunotu);
        System.out.println(pazartesi.ikinciders);
        System.out.println("ödev");
        System.out.println(edebiyat.odev);
        System.out.println("giren hoca");
        System.out.println(edebiyat.girenhoca);
        System.out.println("yazılı notu");
        System.out.println(edebiyat.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(edebiyat.sozlunotu);
        System.out.println(pazartesi.ucuncuders);
        System.out.println("ödev");
        System.out.println(beden.odev);
        System.out.println("giren hoca");
        System.out.println(beden.girenhoca);
        System.out.println("yazili notu");
        System.out.println(beden.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(beden.sozlunotu);
        System.out.println("salı");
        System.out.println(sali.birinciders);
        System.out.println("ödev");
        System.out.println(ingilizcewriting.odev);
        System.out.println("giren hoca");
        System.out.println(ingilizcewriting.girenhoca);
        System.out.println("yazılı notu");
        System.out.println(ingilizcewriting.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(ingilizcewriting.sozlunotu);
        System.out.println(sali.ikinciders);
        System.out.println("ödev");
        System.out.println(resim.odev);
        System.out.println("giren hoca");
        System.out.println(resim.girenhoca);
        System.out.println("yazili notu");
        System.out.println(resim.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(resim.sozlunotu);
        System.out.println(sali.ucuncuders);
        System.out.println("ödev");
        System.out.println(ingilizcewriting.odev);
        System.out.println("giren hoca");
        System.out.println(ingilizcewriting.girenhoca);
        System.out.println("yazili notu");
        System.out.println(ingilizcewriting.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(ingilizcewriting.sozlunotu);
        System.out.println("carsamba");
        System.out.println(carsamba.birinciders);
        System.out.println("ödev");
        System.out.println(matematik.odev);
        System.out.println("giren hoca");
        System.out.println(matematik.girenhoca);
        System.out.println("yazili notu");
        System.out.println(matematik.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(matematik.sozlunotu);
        System.out.println(carsamba.ikinciders);
        System.out.println("ödev");
        System.out.println(ingilizcelistening.odev);
        System.out.println("giren hoca");
        System.out.println(ingilizcelistening.girenhoca);
        System.out.println("yazili notu");
        System.out.println(ingilizcelistening.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(ingilizcelistening.sozlunotu);
        System.out.println(carsamba.ucuncuders);
        System.out.println("ödev");
        System.out.println(ingilzcemaincourse.odev);
        System.out.println("giren hoca");
        System.out.println(ingilzcemaincourse.girenhoca);
        System.out.println("yazili notu");
        System.out.println(ingilzcemaincourse.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(ingilzcemaincourse.sozlunotu);
        System.out.println("perşembe");
        System.out.println(persembe.birinciders);
        System.out.println("ödev");
        System.out.println(edebiyat.odev);
        System.out.println("giren hoca");
        System.out.println(edebiyat.girenhoca);
        System.out.println("yazili notu");
        System.out.println(edebiyat.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(edebiyat.sozlunotu);
        System.out.println(persembe.ikinciders);
        System.out.println("ödev");
        System.out.println(ingilzcemaincourse.odev);
        System.out.println("giren hoca");
        System.out.println(ingilzcemaincourse.girenhoca);
        System.out.println("yazili notu");
        System.out.println(ingilzcemaincourse.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(ingilzcemaincourse.sozlunotu);
        System.out.println(persembe.ucuncuders);
        System.out.println("ödev");
        System.out.println(bilisim.odev);
        System.out.println("giren hoca");
        System.out.println(bilisim.girenhoca);
        System.out.println("yazili notu");
        System.out.println(bilisim.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(bilisim.sozlunotu);
        System.out.println(cuma.birinciders);
        System.out.println("ödev");
        System.out.println(resim.odev);
        System.out.println("giren hoca");
        System.out.println(resim.girenhoca);
        System.out.println("yazili notu");
        System.out.println(resim.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(resim.sozlunotu);
        System.out.println(cuma.ikinciders);
        System.out.println("ödev");
        System.out.println(ingilizcelistening.odev);
        System.out.println("giren hoca");
        System.out.println(ingilizcelistening.girenhoca);
        System.out.println("yazili notu");;
        System.out.println(ingilizcelistening.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(ingilizcewriting.sozlunotu);
        System.out.println(cuma.ucuncuders);
        System.out.println("ödev");
        System.out.println(matematik.odev);
        System.out.println("giren hoca");
        System.out.println(matematik.girenhoca);
        System.out.println("yazili notu");
        System.out.println(matematik.yazilinotu);
        System.out.println("sözlü notu");
        System.out.println(matematik.sozlunotu);


    }}
